version: "3"

services:
  docker:
    build:
      context: ./examples
      dockerfile: ./docker.dockerfile
    volumes:
      - $PWD/examples/scripts:/home/conf.json
      - $PWD/examples/conf.json:/home/conf.json
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7770:3000

